function cfg = default_config()
%DEFAULT_CONFIG Public-safe minimal configuration template.

cfg = struct();

cfg.network = struct(...
    'server_host', '127.0.0.1', ...
    'server_port', 8080, ...
    'tcp_timeout_sec', 5.0);

cfg.hardware = struct(...
    'arduino_com_port', 'COM_PORT_PLACEHOLDER', ...
    'arduino_baud', 115200, ...
    'enable_arduino', false, ...
    'enable_ophir_energy', false);

cfg.shared_memory = struct(...
    'file_path', fullfile(tempdir, 'shared_image_data_public.dat'), ...
    'max_packages', 128, ...
    'image_width', 1792, ...
    'image_height', 128, ...
    'num_wavelengths', 4, ...
    'frames_per_wavelength', 4);

cfg.logging = struct(...
    'base_dir', fullfile(fileparts(mfilename('fullpath')), '..', 'logs'), ...
    'verbose', true);

cfg.modes = struct(...
    'simulation_only', true, ...
    'package_layout_mode', 'cyclic');
end
