function hw = hardware_config_template()
%HARDWARE_CONFIG_TEMPLATE Fill this with your actual hardware mapping.

hw = struct();
hw.arduino_com_port = 'COM_PORT_PLACEHOLDER';
hw.arduino_baud = 115200;

hw.verasonics = struct(...
    'probe_name', 'TODO_PROBE_NAME', ...
    'center_frequency_mhz', 7.0, ...
    'num_tx_channels', 128, ...
    'num_rx_channels', 128);

% Energy compensation is intentionally disabled in this public draft.
hw.ophir = struct(...
    'enable', false, ...
    'channel', 0);
end
